name: test library

on:
  push:
    paths:
      - '**.go'
      - 'go.mod'
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Dependency
        run: go mod tidy

      - name: Test
        run: go test -v .